baseURL = "https://github.com/marcomattolab/marcomartorana/"
DefaultContentLanguage = "it"
defaultContentLanguageInSubdir = false
languageCode = "it"
title = "Marco Martorana"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
pagination.pagerSize = 10
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "Marco Martorana"
  website = "https://www.marcomartorana.it/"
  authorInfo = "Software Engineer | Computer Science Teacher"
  authorPostImage = "/img/author-post-img.jpg"

[Author]
  name = "Marco Martorana"
  website = "https://marcomartorana.it"
  email = "marcomatto@gmail.com"
  facebook = "profile.php?id=100091312733657"
  instagram = "marcomartorana.lab"
  youtube = "@MarcoMartorana"
  twitter = "marcomattox"
  linkedin = "marcomartorana"
  github = "marcomattolab"
  paypal = "markmartorana?country.x=IT&locale.x=it_IT"
  #twitch = "https://www.twitch.tv/marco_martorana"
  #telegram = "@Marcomatto"
  #threads = "username"
  #gitlab = "https://marcomattolab.github.io/"
  #reddit = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #spotify = "username"
  #mastodon = "url"
  #slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  #codepen = "username"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "School"
    url = "/tags/school/"
    weight = 3

[[menu.main]]
    name = "Meetings"
    url = "/meetings/"
    weight = 4

[[menu.main]]
    name = "Informatics"
    url = "/informatics/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
