name: Hugo Build & Deploy - Private to Public repo

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Hugo
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: false

    # Runs Hugo to build the Static Site             
    - name: Build
      run: hugo --gc --minify  --logLevel info 

    # Deploy the Static Site to Public Repo (GitHub Pages)
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
